### ISSUE TITLE
ANAEE L&F customization

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/ckanext-c195#16]
This is the actual work to be done.
We need a very basic customization of the CKAN L&F that will harmoze it with the guidelines and appearance of the *ANAEE* european project.The reference site for which we should try to resemble the l&f is [this one](https://www.anaee.eu/).

There is material in the project dropbox folder but I think we are ok with simply grabbing things from the website.

**Comment by simboss** [comment]
@luorlandini move on with this one please...

**Comment by luorlandini** [comment]
Hi, 
I started with the customization of the CKAN L&F,
following ANAEE appearances.

I share here some screenshots.


![screencapture-localhost-5000-dataset-2021-03-01-17_42_09](https://user-images.githubusercontent.com/4085786/109533594-b1c64980-7aba-11eb-90c2-c42f0128fcb9.png)
![screencapture-localhost-5000-dataset-meteorological-data-from-the-taastrup-climate-and-water-balance-station-2014-2019-resource-8ac161c3-0322-47b1-8b70-98ffdcb9d8ec-2021-03-01-17_27_35](https://user-images.githubusercontent.com/4085786/109533597-b2f77680-7aba-11eb-8c7d-00830e41c65a.png)
![screencapture-localhost-5000-dataset-meteorological-data-from-the-taastrup-climate-and-water-balance-station-2014-2019-2021-03-01-17_02_17](https://user-images.githubusercontent.com/4085786/109533600-b3900d00-7aba-11eb-8b5a-7490cab449f5.png)

**Comment by simboss** [comment]
@luorlandini can you share a screenshot of the homepage?

**Comment by luorlandini** [comment]
the HP 
![screencapture-localhost-5000-2021-03-01-18_34_05](https://user-images.githubusercontent.com/4085786/109537399-200d0b00-7abf-11eb-825f-f025db348ed2.png)

**Comment by simboss** [comment]
@luorlandini as per our discussion on skype, can you optimize the images we are showing on the home page further?

**Comment by simboss** [comment]
closing
