### ISSUE TITLE
Prepare a plan for the DEV/TEST CKAN installation for CREA

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/ckanext-c195#2]
Basic Information
===
- The platform of choice is MS Azure. The client has a tight relationship with MS.

STEP 1
====
- While this is not a PROD instance I would want to perform an installation that try to mimics PROD as closely as possible
  - We shall use Azure PostgreSQL
  - We shall try to use Docker where applicable
  - We shall try to integrate ASAP with Azure Directory services (this requires more investigation and a discussion with the client)  
- We shall start with a super basic customization of the GUI and then, in time talk about a more refined customization

STEP 2
====
  - We shall think about HA and Scalability. As an instance, we shall try to use a scalable SOLR service; even though there isn't a MS managed services AFAIK, there are various options in the marketplace.
- We shall have CI-CD in place, possibly using Azure Pipelines
- We shall use some sort of automation for the deployment (terraform, helm charts, anything)  **--> OPTIONAL**
- Authentication in CKAN should be performed with Azure Directory Services. **SSO** is also a nice to have feature, but it is really low priority at the moment.

**Comment by simboss** [comment]
@etj we need this to be presentable by the next meeting which is 26/11 11:30

**Comment by simboss** [comment]
@etj can you put the documents you are preparing in this issue as a comment?

**Comment by etj** [comment]
Tasklist: https://docs.google.com/spreadsheets/d/1ywhLIrEtldMDEK4APTtcar5OKyHLpsjQjdivx3KZxxE/edit#gid=376642658

Deployment diagram: https://docs.google.com/drawings/d/1d_4ufnDJRNgWRnFhPMGPfnhlTgHLBJd8uhipmW-Nvh0/edit

Test deploy steps:
https://docs.google.com/document/d/1I5zWPSVR7yxQQfwBRfbFM4IH8G1HDz7ayahBlC5DoWk/edit
